### ISSUE TITLE
I want those colors so hard

### ISSUE THREAD

**Issue by MrMarvel** [create-juicey-app/wantyougone#3]

**Comment by cloudcloudskies** [comment]
Which colors?

**Comment by MrMarvel** [comment]
Color theme for powershell profile

**Comment by MrMarvel** [comment]
https://github.com/create-juicey-app/wantyougone/pull/4
I created pull request with theme for powershell.

**Comment by MrMarvel** [comment]
Recreated pull in #6

**Comment by create-juicey-app** [comment]
Im now going to send the theme
