### ISSUE TITLE
'/c' not working

### ISSUE THREAD

**Issue by Elury15** [create-juicey-app/wantyougone#8]
Hi, I'm currently trying to make my own lyrics and I've noticed that the '/c' command to clear the screen doesn't work, even in the original lyrics.txt. When it encounters it, it returns "TERM environment variable not set". I have tried looking for cues on wantyougone.py but I'm not really experienced with coding so I didn't found how to make it work. Do you have suggestions ?

**Comment by create-juicey-app** [comment]
I see what's happening, you're running this on another OS than windows, I haven't tested Linux yet, but if you can, could you modify the code locally so that you replace the part 

`for line in lyrics.split("\n"):
    if '/c' in line:
        os.system('cls' if os.name == 'nt' else 'clear')`
By 
`for line in lyrics.split("\n"):
    if '/c' in line:
        os.system('clear')`
This will fix your issue. Tell me if there's something wrong then I'll get back to you

**Comment by Elury15** [comment]
Thanks for your reply, I did test it with only 'clear' but it still gives the same error. I also tried writing the /c with different variations, like doing:
text
/c
text

text

/c
text

text

/c

text

Probably doesn't have any impact but after testing all 3 none worked... Also, I'm on Ubuntu so maybe it works differently but it shouldn't be too different from Linux so idk.

**Comment by create-juicey-app** [comment]
Okay this is wierd, my shitty code is fighting against me
may i get your repo?

**Comment by Elury15** [comment]
Srry I just joined github so I don't know much about it
I believe you're talking about 'repository' is this a thing to post the code ?
(sinon je suis aussi fr donc ça peut être + simple comme ça mdr)

**Comment by create-juicey-app** [comment]
> Srry I just joined github so I don't know much about it I believe you're talking about 'repository' is this a thing to post the code ? (sinon je suis aussi fr donc ça peut être + simple comme ça mdr)

oh bah super
genre donne moi ton lyrics.txt

**Comment by Elury15** [comment]
[lyrics.txt](https://github.com/create-juicey-app/wantyougone/files/14951626/lyrics.txt)
J'ai mis le texte mais j'ai pas encore ajusté les délais avec la musique mais ça je le ferais plus tard en faisant des tests

**Comment by create-juicey-app** [comment]
Kk, je vais voir le prob
Edit : nice. Still alive

**Comment by Elury15** [comment]
Salut, je sais que ça fait un certain temps mais je tente quand même : j'ai essayé d'examiner le code mais je n'ai pas le niveau pour arriver à faire marcher ça moi-même. Est-ce que tu pourrais y jeter un coup d'œil stp ?

**Comment by create-juicey-app** [comment]
ne t'embette pas
utilise chatgpt
